theme: minima
title: Bit about myself...
author: Hakim 'Azizan 
email: hazizan22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about myself and journey about how i started to dive into the world of computer science and information technologies.

# social links
twitter_username: HakimAzizan98 # DO NOT include the @ character, or else the build will fail!
github_username:  hakim222 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
